tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"

brew "chruby"
brew "fzf"
brew "jq"
brew "lazygit"
brew "lua-language-server"
brew "luarocks"
brew "neovim"
brew "ripgrep"
brew "ruby-install"
brew "shellcheck"
brew "tmate"
brew "tmux"
brew "watchman"

cask "dozer"
cask "droidcam-obs"
cask "elgato-control-center"
cask "elgato-stream-deck"
cask "font-fira-code-nerd-font"
cask "kitty"
cask "lunar"
cask "ngrok"
cask "obs"
cask "soundsource"
cask "raycast"
