tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"

brew "chruby"
brew "fzf"
brew "jq"
brew "lazygit"
brew "neovim"
brew "ripgrep"
brew "ruby-install"
brew "shellcheck"
brew "tmux"
brew "watchman"

cask "font-fira-code-nerd-font"
cask "hammerspoon"
cask "kitty"
cask "soundsource"
