#!/usr/bin/env ruby
# frozen_string_literal: true

require "find"
# find seems to walk files sorted alphabetically so we might need to load base before e.g. apt)
require_relative "lib/base"

Find.find(File.join(File.expand_path(__dir__), "lib")) do |file|
  next if File.extname(file) != ".rb"

  load(file)
end

class Dotfiles
  def run
    Apt.new.run
    Homebrew.new.run

    Kitty.new.run
    Tmux.new.run
    Zsh.new.run
    NeoVim.new.run

    LastRun.instance.update
  end
end

Dotfiles.new.run
