#!/usr/bin/env ruby

require "find"
require_relative "lib/base" # find seems to walk files sorted alphabetically so we might need to load base before e.g. apt)

Find.find(File.join(File.expand_path(__dir__), "lib")) do |file|
  next if File.extname(file) != ".rb"
  load(file)
end

class Dotfiles
  def run
    Apt.new.run
    Homebrew.new.run

    Kitty.new.run
    Tmux.new.run
    Zsh.new.run
    NeoVim.new.run

    LastRun.instance.update
  end
end
  
Dotfiles.new.run
