#!/usr/bin/env bash

set -euo pipefail

sudo apt-get remove -y neovim
sudo apt-get install -y python3-pip

# Fetch App Image for NeoVim
NVIM_VERSION="v0.7.0"
cd /usr/local/src
sudo rm -rf nvim.appimage squashfs-root
sudo wget "https://github.com/neovim/neovim/releases/download/${NVIM_VERSION}/nvim.appimage"
sudo chmod u+x nvim.appimage
sudo ./nvim.appimage --appimage-extract
sudo rm -f /usr/local/bin/nvim
sudo ln -s $PWD/squashfs-root/usr/bin/nvim /usr/local/bin/nvim

pip3 install neovim
sudo gem install neovim
npm -g install neovim
