---
name: Update gem RBIs on Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'Gemfile.lock'

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  update-gem-rbis:
    runs-on: ubuntu-latest
    if: ${{ contains(github.actor, 'dependabot[bot]') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{secrets.DEPENDABOT_RBI_ACCESS_TOKEN}}
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install os dependencies
        run: >
          sudo apt-get update -qq &&
            sudo apt-get install --no-install-recommends -y build-essential git libpq-dev libvips pkg-config
      - name: Update gem RBIs
        run: bin/tapioca gem
      - name: Update gem annotations
        run: bin/tapioca annotations
      - name: Check for changes
        id: check-for-changes
        run: |
          status=$(git status sorbet --porcelain=v1)
          echo "changes=$([ -n "$status" ]; echo $?)" >> $GITHUB_OUTPUT
      - name: Commit changes
        if: ${{ steps.check-for-changes.outputs.changes == '0' }}
        run: |
          git config user.name "Tobias Bales [bot]"
          git config user.email "github-bot@tobiasbales.com"
          git add sorbet/*
          git commit -m "Update gem RBIs [dependabot skip]"
          git push
